# Generated by Django 3.2.14 on 2022-07-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amigos', '0002_auto_20220724_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amigo',
            old_name='email_amigo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='amigo',
            old_name='nome_amigo',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='amigo',
            old_name='sugestao_presente_amigo',
            new_name='sugestao_presente',
        ),
        migrations.RenameField(
            model_name='amigo',
            old_name='telefone_amigo',
            new_name='telefone',
        ),
    ]
