# Generated by Django 3.2.14 on 2022-07-24 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('amigos', '0003_auto_20220724_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='amigo',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
